### ISSUE TITLE
Pre-proposal: Adopting a text-based diagram syntax in Jupyter Markdown

### ISSUE THREAD

**Issue by bollwyvl** [jupyter/enhancement-proposals#100]
## Elevator Pitch

_Jupyter Markdown_ should adopt a text-based syntax for building diagrams. Flagship Jupyter tools like _JupyterLab 4_, _Jupyter Notebook 7_, _nbconvert_, and _nbviewer_ should render this syntax consistently.

## Scope of proposal

The proposal will evaluate the merits of (in no particular order):

- portability to other Markdown-generating and -consuming platforms 
- maturity of the implementation
- accessibility
- security
- performance
- maintenance/dependency burden
- breadth of diagrams and expressive power

## Prior Art

Some links to existing work that will inform the proposal:

- https://github.com/jupyterlab/jupyterlab/pull/14102
- https://github.com/jupyter/nbconvert/pull/1957
- https://github.com/jupyter/software-steering-council-team-compass/issues/1

<details>

<summary><h3>SPOILERS<h3></summary>

The proposed implementation is [mermaidjs 10](https://mermaid.js.org/). 

The proposed syntax is the one implemented in the most places, based on GitHub fenced code blocks:

    ```mermaid
    flowchart LR
        chicken --> egg --> chicken
    ```

</details>

**Comment by krassowski** [comment]
The associated JEP is https://github.com/jupyter/enhancement-proposals/pull/101

**Comment by gabalafou** [comment]
As part of triage in working call today, closing this as it has an associated JEP (#101).
