### ISSUE TITLE
Pre-proposal: subdomain for published schemas under jupyter.org

### ISSUE THREAD

**Issue by Zsailer** [jupyter/enhancement-proposals#107]
(Following the [JEP submission workflow described here](https://jupyter.org/enhancement-proposals/jupyter-enhancement-proposal-guidelines/jupyter-enhancement-proposal-guidelines.html#jep-submission-workflow), but there's been a substantial amount of discussion already around this idea.)

I'm drafting a JEP to propose a new subdomain under jupyter.org, e.g. schema.jupyter.org, where we can **publish** json schemas describing key components, APIs, and data files defined across Project Jupyter. Examples include event schemas, kernel specification, connection file specification, kernel messaging specification, notebook file format specification, and the Jupyter Server and JupyterHub REST APIs.

Publishing these as JSON schemas ensures that we explicitly publish our "contracts" to the community and enables us to write tooling that helps others validate their code against our schemas. 

Key pieces that might be included in this JEP:
- where should schemas be stored?
- URI rules... e.g. every URI should be versioned; namespace by project; (maybe) namespace by current state (e.g. experimental/stable)
- governance: who publishes to this repo?

I'm planning to submit this JEP this week, but starting the pre-proposal process here.

**Comment by bollwyvl** [comment]
Very much in favor of moving this forward.

As mentioned elsewhere: I feel like the repo that drives this (and feel like it _should_ be _one_ repo, even if it submodules in "canonical" sources of schema) should also drive the publishing of installable packages, with a selection of:
- the schemas-at-rest in JSON
  - probably somewhere in `{sys.prefix}/share/jupyter`
- type-only packages with no depedencies for any willins languages
- and even ones for specific, _de facto_ validator implementations (e.g. python's `jsonschema`, JS `ajv`)
  - a la [jsonschema-specifications](https://pypi.org/project/jsonschema-specifications)

The above should also generate (and validate) per-PR interlinked human-readable docs, which can then expose something that other docs sites can reference (e.g. `objects.inv`), such as provided by:
- [sphinx-jsonschema](https://pypi.org/project/sphinx-jsonschema/), [sphinxcontrib-openapi](https://github.com/sphinx-contrib/openapi), [asyncapi-sphinx-ext](https://asyncapi-sphinx-ext.readthedocs.io) (but... boo rst)
- [jsonschema2md](https://github.com/adobe/jsonschema2md)
- `mkdocs` with `mkdocstrings`
  - apparently no package yet for some of these flavors

By keeping them together, we can maintain:
- consistent linting and formatting
- cross-language build toolchains
- meta(-meta) schema to validate these things 
- normalize more humane alternative _authoring_ tooks (e.g. YAML, TOML, some notebook workflow)

**Comment by Zsailer** [comment]
@bollwyvl do you mind if I copy these points to the JEP and add you as a co-author (want to make sure I give credit where credit is due!).

**Comment by Zsailer** [comment]
I've got a working draft here: https://hackmd.io/@eesn0xIhTWeoLTbVbbhpdA/ByfCRmV72/edit

**Comment by Zsailer** [comment]
Woohoo! Thank you, @bollwyvl and @tonyfast for all the amazing work on developing a first draft of this proposal!! I'm opening the PR now 😎

**Comment by bollwyvl** [comment]
Thanks! We started noodling on some of those ideas in greater anger in the "Future of Notebooks" workshop and the attendant "Cells from the Future" weekly. As the terminating output of that call would be rather... sweeping... having a more structured place than _this_ narrative-based repo would be super helpful.

There's a lot of opportunity/risk for scope creep on this, but in the end, it's probably for the best, but I didn't want to put _all_ of the ideas into that JEP. Once we've got our feet under us, building packages (which i kind of feel is really the ["final exam"](https://en.wikipedia.org/wiki/George_H._Heilmeier#Heilmeier's_Catechism) of that JEP) there's probably a whole raft of things that can be further formalized, but were out of scope for that document.

- directory structures of well-known paths
  - while i don't _know_ of a solid, cross-platform schema for describing file trees, this would be a boon for complex deployments to `.d` folders, and confections like `lab/extensions`
- binary structures
  - [kaitaistruct](https://kaitai.io/) provide a way to document these outside of magic numbers in reference implementations, with limited codegen 
- grammars
  - it's looking like [lark](https://github.com/lark-parser/lark) might end up being a real possibility for portable grammar descriptions
  - examples
    - even if "All Of Markdown" can't be described by a grammar, the _block level_ one _probably can_ 
      - this would allow for precisely describing e.g. #101
    - magics and other extraplanar syntax by kernels
    - syntax highlighting
- non-purely-declarative inputs
  - schema-as-code
    - `pydantic`, `dataclasses`, etc. provide opinonated ways to ergonomically write schema beyond TOML/YAML
    - [construct](https://construct.readthedocs.io) similarly allows for defining
    - more generally, a `.schema.ipynb`, where the _outputs_ are the schema, might be quite interesting
  - migrations-as-data
    - tools like [json-e](https://json-e.js.org/), we could describe closed-form, declarative migrations between schema versions
- well-known mimetype
  - while the "high road" is IANAL, that's... a long road, and can leave things in a chicken and egg
  - this would show up all the way at the bottom of the stack in kernelspecs (#105) and all the way at the end
- DOM validation
  -  XSLT could be used to verify that a given HTML-like output (either a client, static, or... some other thing) has agreed-upon characteristics 
    - appropriate `aria-*` annotation would be _huge_, and should likely be _the_ abstract design language for Jupyter clients and documents
