### ISSUE TITLE
Accepting proposals as drafts

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/enhancement-proposals#11]
Rather than go back and forth in a PR to accept a proposal, how about we accept a PR and call it a `draft` state. When we've accepted it, we make a PR to update the status. If it's deprecated, not implemented, etc. we make another PR to address that.

**Comment by minrk** [comment]
Fine with me.

**Comment by captainsafia** [comment]
I'll update the wording of the guidelines to reflect this later today.

**Comment by rgbkrk** [comment]
Cool. I'm thinking similar to how https://github.com/tc39/ecma262 works, though they [call them stages](https://tc39.github.io/process-document/). Taking parallels to other projects, zeromq uses:

* `draft`: Has at least one implementation
* `stable`: Deployed to real users
* `legacy`: Being replaced by newer specs
* `retired`: Replaced, no longer used
* `deleted`: Abandoned before becoming stable

Some proposals end up as PRs to individual repos (e.g. jupyter/notebook, jupyter/nbformat) while others may end up as wholly new projects. I'm not sure what this means for how we phrase these.

**Comment by ellisonbg** [comment]
Maybe move this process discussion over to the governance repo?

Like the direction though...

On Sun, Feb 7, 2016 at 8:38 AM, Kyle Kelley <notifications@github.com>
wrote:

> Cool. I'm thinking similar to how https://github.com/tc39/ecma262 works,
> though they call them stages <https://tc39.github.io/process-document/>.
> Taking parallels to other projects, zeromq uses:
>
>    - draft: Has at least one implementation
>    - stable: Deployed to real users
>    - legacy: Being replaced by newer specs
>    - retired: Replaced, no longer used
>    - deleted: Abandoned before becoming stable
>
> Some proposals end up as PRs to individual repos (e.g. jupyter/notebook,
> jupyter/nbformat) while others may end up as wholly new projects. I'm not
> sure what this means for how we phrase these.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/enhancement-proposals/issues/11#issuecomment-181046207>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by nealmcb** [comment]
How might this relate to #27?

**Comment by rgbkrk** [comment]
Extremely related. Since that's a newer discussion with the same folks, I'll close this one.
