### ISSUE TITLE
Set suggested time periods for RFC and voting phases

### ISSUE THREAD

**Issue by Zsailer** [jupyter/enhancement-proposals#112]
In today's SSC meeting, we discussed defining (and explicitly documenting) **"suggested" time lengths** for the RFC and voting periods. This encourages the SSC to review proposals in a timely manner and it helps JEP authors have a sense of the level of engagement they should expect before committing the energy to drafting a JEP. 

Historically, JEPs have been left open indefinitely; I think this discourages folks from submitting JEPs. I'm hoping to improve this experience.

I mentioned in today's meeting that aiming for a total ~6 week time seems reasonable (though open to discussion here) for a proposal to be opened until final vote is reached. I was thinking 4 weeks for RFC and 2 weeks for voting. These specific numbers are meant to be guidelines; the actual timeframes should be set by the JEP shepherd. If a JEP's impact is larger, the time for each phase can be extended. Otherwise, the JEP defaults to these time periods. 

I'm planning to submit a PR to our documentation with these details later this week but wanted to give folks a chance to comment before that.

**Comment by JohanMabille** [comment]
Closing as this has been implemented in [the reviewed JEP process](https://github.com/jupyter/enhancement-proposals/pull/104).
