### ISSUE TITLE
Discourse favoured to Forum 

### ISSUE THREAD

**Issue by echarles** [jupyter/enhancement-proposals#59]
Further a chat with @yuvipanda related to deprecation of the jupyter google forum (https://groups.google.com/forum/#!forum/jupyter) in favor to Discourse (https://discourse.jupyter.org), I open this issue so that (if we want it like that) this is better announced on the forum and users post their questions on discourse.

<img width="484" alt="Screenshot 2020-06-24 at 14 33 53" src="https://user-images.githubusercontent.com/226720/85558532-1c201380-b629-11ea-9f0f-572de7417aa2.png">

An easy way would be to update the forum description from 'Mailing list for jupyter-related projects` to `Deprecated Mailing list for jupyter-related projects - Please use https://discourse.jupyter.org`

e.g. see the last question (see screenshot) on Panel and JupyterHub may find more echo on discourse.

A secondary question is whether the announce of new releases should continue to be published on the forum. (pinging @kevin-bates who has done an incredible job on the notebook release and has just announced it 👍  ).

**Comment by choldgraf** [comment]
Hey @echarles - thanks for raising the issue. Just to clarify - do you wish for this issue [to be a JEP](https://jupyter.org/enhancement-proposals)?

I think that I'm +1 on suggesting that people use the community forum, but I don't think we should call the mailing list "deprecated". Perhaps instead we can post semi-regular posts to the mailing lists encouraging people to use the community forum, and over time if the traffic there dies down, we can eventually deprecate it.

**Comment by echarles** [comment]
@choldgraf I am not aiming for a JEP, but did not really know where to open something for this. Where should I have done that? Regarding the wording, yeah, no strong opinion on that but `deprecated` does not sound very good...

**Comment by westurner** [comment]
Possibly orthogonal, but relevant to any clarifying statement about where we prefer certain types of communications:

A quick [search for "Jupyter security disclosure"](https://www.google.com/search?q=jupyter+security+disclosure? returns this as the first result
https://jupyter-notebook.readthedocs.io/en/stable/security.html ; which mentions security@jupyter.org . Is that the current security disclosure list?

https://en.wikipedia.org/wiki/Security.txt ::
> security.txt is a proposed standard for websites' security information that is meant to allow security researchers to easily report security vulnerabilities.[1][2] The standard prescribes a text file called "security.txt" that is similar to robots.txt but intended to be read by humans wishing to contact a website's owner about security issues.[3] security.txt files have been adopted by Google, GitHub, LinkedIn, and Facebook.[4]

Speaking of robots.txt, how search-indexed is the discourse forum as compared with the mailing list, stackoverflow, etc?

- https://stackoverflow.com/questions/tagged/jupyter
- https://stackoverflow.com/questions/tagged/jupyter-notebook

Is there already a Communications Plan that clarifies which channels are usually used for which communications; which could be consistently linked to when directing folks to where they'd be most likely to get heard and have maximum impact?

https://jupyter.org/community also mentions security@ipython.org .

Do all of the CONTRIBUTING.md files reference SECURITY.txt and the e.g.Jupyter Communications Plan?

**Comment by blink1073** [comment]
Hi @westurner, thanks for pointing to these standards!  I am curious, when I load https://jupyter-notebook.readthedocs.io/en/stable/security.html  I only see security@ipython.org (not security@jupyter.org).  The [source](https://github.com/jupyter/notebook/blob/master/docs/source/security.rst#reporting-security-issues) also has security@ipython.org.

**Comment by SylvainCorlay** [comment]
(In a triage session in the public SSC working call.)

It seems that this issue should be opened in the repository https://github.com/jupyter-governance/ec-team-compass, since it cannot be decided by the SSC, which can only vote on JEPs.
