### ISSUE TITLE
JEP: Notebook v7

### ISSUE THREAD

**Issue by fperez** [jupyter/enhancement-proposals#78]
The transition from the version 6 of the notebook to a future version 7, based on the modern JupyterLab codebase, has been already extensively discussed in our community. Given there have been multiple open issues (listed below), meetings and discussions about this already, I'm shortcutting a bit here by moving directly to creating a JEP PR for this topic. But in case there's any concerns folks would like to address here outside of discussing the JEP proper, I'm opening this issue for the time being.

To keep things focused, any material discussion of the JEP body itself should go into the PR, not here.

Previous issues of relevance:

* [[Discuss] The future of the classic notebook interface](https://github.com/jupyter/notebook/issues/6210).
* [Proto-JEP](https://github.com/jupyter/notebook/issues/6220).
* [Early draft of the JEP in my fork, that was edited by all the JEP co-authors](https://github.com/fperez/enhancement-proposals/pull/1).

**Comment by jasongrout** [comment]
The JEP has been accepted and the JEP PR merged (#79).
