### ISSUE TITLE
[PRE-PROPOSAL] Jupyter UI Components

### ISSUE THREAD

**Issue by echarles** [jupyter/enhancement-proposals#88]
The JEP will propose the adoption of well defined `UI Components` across Jupyter projects that need to build user interfaces. While being primarily focussed on [Web Component](https://developer.mozilla.org/en-US/docs/Web/Web_Components) and [React.js](https://reactjs.org) technology, the creation of components based on other technologies like [Vue.js](https://vuejs.org), [Svelte](https://svelte.dev)... will be possible.

The deliverable will be the creation of a `ui-components` repository providing accessible and themed widgets fully compatible with React.js, without blocking usage by other popular frontend technologies.

On top of those components, extended functionalities on `reactivity` and `collaboration` are also discussed here. But they are out-of-scope of the deliverable. It makes sense to already discuss those last aspects in relationship with [Jupyter Widgets](https://github.com/jupyter-widgets) and the current JupyterLab Realtime collaboration features.

Accessibility criteria will drive the creation of those components.

We propose to move the current https://github.com/jupyterlab-contrib/jupyter-ui-toolkit repository to a Jupyter top-level repository. The home of that repository and the npm.js package naming still needs to be defined. That repository will be advertised as the default way to build user interface that conform to the Jupyter guidelines.

The draft proposal can be read on https://github.com/datalayer/jupyter-react/tree/jep/jep

Proposed Shepherd: @echarles (from this [doc](https://jupyter.org/enhancement-proposals/jupyter-enhancement-proposal-guidelines/jupyter-enhancement-proposal-guidelines.html#phase-1-pre-proposal), I am not sure if the shepherd needs to be part of any specific Jupyter org?)

Proposed Review Team: @fcollonval @jtpio @isabela-pf @tonyfast @gabalafou

**Comment by echarles** [comment]
I realise that the current draft JEP lacks requirements for Accessibility (just stated as goal for now), therefor we need more eyes and expertise.

I'd like to add to the `Proposed Review Team` members @isabela-pf @tonyfast @gabalafou to help on that difficult and important accessibility matter.

**Comment by echarles** [comment]
Thx @damianavila for fixing the title and @isabela-pf for contributions related to accessibliity.

Let's wait next week for more feedbacks before going to the proposal phase.

**Comment by gabalafou** [comment]
Hi @echarles, impressive work on the draft JEP! I just submitted a PR with some edits and comments: https://github.com/datalayer/jupyter-react/pull/12

**Comment by echarles** [comment]
This pre-proposal has not progressed. I proposed to close it in a few days unless community get interested by then.
